name: Nodejs Typescript CD
on:
  workflow_run:
    workflows: ["Check & Create PR"]
    types:
      - completed
  push:
    branches:
      - dev
      - homolog
      - prod
jobs:
  DeployToAWS:
    environment:
      name: ${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Setup AWS Credentials
        run: |
          echo "Configuring AWS Credentials"
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          aws configure set default.output json
      - name: Setting stage, stack name
        run: |
          echo "STACK_NAME=${{ secrets.STACK_NAME }}${{ github.ref_name }}" >> $GITHUB_ENV
          echo "MONGO_URI=${{ secrets.MONGO_URI }}${{ github.ref_name }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Installing Dependencies
        run: |
          cd server
          yarn
          cd iac
          npm install -g aws-cdk ts-node
          npm i
      - name: Setup envs
        run: |
          echo AWS_REGION=${{ secrets.AWS_REGION }}>> $GITHUB_ENV
          echo STACK_NAME=${{ env.STACK_NAME }} >> $GITHUB_ENV
          echo GITHUB_REF_NAME=${{ github.ref_name }} >> $GITHUB_ENV
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> $GITHUB_ENV
      - name: CDK Bootstrap
        run: |
          echo "CDK Bootstrap"
          cd iac
          aws cloudformation describe-stacks --stack-name CDKToolkit 2>&1 > /dev/null || \
            cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/sa-east-1
      - name: Deploy with CDK
        run: |
          source $GITHUB_ENV
          yarn build
          cd iac
          ts-node node_modules_adjust.ts
          
          cdk synth
          cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          MONGO_URI: ${{ secrets.MONGO_URI }}